
/*
    Creates a table.
    Takes table name and sql command as parameters and print the required table.
*/
package com.yamkela22y.databaseConnection;

import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author yamkela
 */
public class DataTable_db extends javax.swing.JPanel {


    /**
     * Creates new form DataTable
     * @param sql_comm
     */
    public DataTable_db(String sql_comm) {
        initComponents();
        new TableAccess().tableLoad(dataTable, sql_comm);
    }
    
    /**
     * Creates new form DataTable
     */
    public DataTable_db() {
        initComponents();
    }
    
    
    /**
     * To print or save the data from the table loaded form the database.Uses tableLoad() to print or save the required tables.It prints the default table.
     * @param sql_comm 
     */
     public void printTable(String sql_comm){
            MessageFormat header = new MessageFormat("Register");
            MessageFormat footer = new MessageFormat("Page{0, number, integer}");
            try{
                new TableAccess().tableLoad(dataTable,sql_comm);
                dataTable.print(JTable.PrintMode.NORMAL,header,footer );
            }
            catch(PrinterException e){
                JOptionPane.showMessageDialog(null,e);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dataTable.setOpaque(false);
        jScrollPane2.setViewportView(dataTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
