/*
 * This class allows the user to search the database based on the required data,
 * i.e Search by: School name, Location, or date.
 * It also allows the user to print/save the table.
*/
package com.yamkela22y.databaseConnection;

import com.yamkela22y.dashboard.scrollbar.ScrollBarCustom;
import com.yamkela22y.swing.PanelTransparent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author yamkela
 */
public class FindRec extends PanelTransparent {

    /**
     * Creates new form FindRec
     */
    public FindRec() {
        initComponents();
        setTransparent(0.5f);
        //Cunstomize the default scrollpane
        table1ScrollPane.setVerticalScrollBar(new ScrollBarCustom()); 
        new TableAccess().tableLoad(table1, "SELECT first_name, last_name, location, school, phone_No , rec_date FROM reg");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        searchField = new javax.swing.JInternalFrame();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnSearch = new javax.swing.JMenu();
        mnDate = new javax.swing.JMenuItem();
        mnLocation = new javax.swing.JMenuItem();
        mnSchool = new javax.swing.JMenuItem();
        printButton = new com.yamkela22y.swing.ImageAvatar();
        table1ScrollPane = new javax.swing.JScrollPane();
        table1 = new com.yamkela22y.dashboard.table.Table();

        jDesktopPane1.setOpaque(false);

        searchField.setBackground(new java.awt.Color(204, 204, 204));
        searchField.setBorder(null);
        searchField.setFocusCycleRoot(false);
        searchField.setFrameIcon(null);
        searchField.setVisible(true);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));

        mnSearch.setBackground(new java.awt.Color(204, 204, 204));
        mnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_26px.png"))); // NOI18N
        mnSearch.setMinimumSize(new java.awt.Dimension(500, 32));
        mnSearch.setPreferredSize(new java.awt.Dimension(100, 32));
        mnSearch.setRolloverEnabled(false);

        mnDate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnDate.setText("Date");
        mnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDateActionPerformed(evt);
            }
        });
        mnSearch.add(mnDate);

        mnLocation.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnLocation.setText("Location");
        mnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLocationActionPerformed(evt);
            }
        });
        mnSearch.add(mnLocation);

        mnSchool.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnSchool.setText("School");
        mnSchool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSchoolActionPerformed(evt);
            }
        });
        mnSearch.add(mnSchool);

        jMenuBar1.add(mnSearch);

        searchField.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout searchFieldLayout = new javax.swing.GroupLayout(searchField.getContentPane());
        searchField.getContentPane().setLayout(searchFieldLayout);
        searchFieldLayout.setHorizontalGroup(
            searchFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        searchFieldLayout.setVerticalGroup(
            searchFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_icons/printer.png"))); // NOI18N
        printButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printButtonMouseClicked(evt);
            }
        });

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        table1ScrollPane.setViewportView(table1);

        jDesktopPane1.setLayer(searchField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(printButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(table1ScrollPane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(table1ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(table1ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDateActionPerformed
        new TableAccess().searchByDate(table1, "SELECT first_name, last_name, location, school, phone_No , rec_date FROM reg where rec_date = ?");    
    }//GEN-LAST:event_mnDateActionPerformed

    private void mnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLocationActionPerformed
       new TableAccess().searchByLocation(table1, "SELECT first_name, last_name, location, school, phone_No , rec_date FROM reg where location = ?");
    }//GEN-LAST:event_mnLocationActionPerformed

    private void mnSchoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSchoolActionPerformed
         new TableAccess().searchBySchool(table1, "SELECT first_name, last_name, location, school, phone_No , rec_date FROM reg where school = ?");
    }//GEN-LAST:event_mnSchoolActionPerformed

    private void printButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printButtonMouseClicked
         if(table1.getRowCount() == 0){
            JOptionPane.showMessageDialog(jDesktopPane1, "Cannot Print, table is empty.");
        }else{
            MessageFormat header = new MessageFormat("Register");
            MessageFormat footer = new MessageFormat("Page{0, number, integer}");
            try{
                table1.print(JTable.PrintMode.NORMAL,header,footer );
            }
            catch(PrinterException e){
                JOptionPane.showMessageDialog(null,e);
            }
        }
    }//GEN-LAST:event_printButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnDate;
    private javax.swing.JMenuItem mnLocation;
    private javax.swing.JMenuItem mnSchool;
    private javax.swing.JMenu mnSearch;
    private com.yamkela22y.swing.ImageAvatar printButton;
    private javax.swing.JInternalFrame searchField;
    private com.yamkela22y.dashboard.table.Table table1;
    private javax.swing.JScrollPane table1ScrollPane;
    // End of variables declaration//GEN-END:variables
}
