//APS score calculator
package com.yamkela22y;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author YAMKELA MACWILI
 */
public class APSCalculator extends javax.swing.JFrame {

    /**
     * Creates new form APSCalculator
     */
    ImageIcon icon = null;
    ArrayList unis = new ArrayList<>(Arrays.asList("UNISA", "UCT",
            "UP", "CPUT", "NMU", "UJ",
            "WSU", "UFS", "CPUT", "TUT", "CUT", "UFH ", "Rhodes", "UCT ", "SUN", "UP ",
            "UWC", "UMP ", "UL", "UNIZULU", "UKZN", "SPU "));

    public APSCalculator() {
        
        initComponents();
        icon = new ImageIcon("C:\\Users\\yamke\\OneDrive\\NetBeansProjects\\IsiphoRegistrationForm\\src\\app_icons\\Background_images\\isiphoLogo_icon.jpg");
        setIconImage(icon.getImage());
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField24 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        btnSubmit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("APS Score");
        setIconImages(null);
        setLocation(new java.awt.Point(400, 100));
        setSize(new java.awt.Dimension(350, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APS Score Calculator", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(102, 0, 0))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(380, 589));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Afrikaans HL");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel3.setPreferredSize(new java.awt.Dimension(79, 16));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 200, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Afrikaans FAL");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, 20));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 50, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 50, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setText("IsiZulu FAL");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("English FAL");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("EnglishHL");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setPreferredSize(new java.awt.Dimension(79, 16));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 200, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText(" IsiZulu HL");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 200, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Agricultural Man. Prac.");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 200, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Business Studies");
        jLabel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("IsiXhosa");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 200, 20));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setText("Civil Technology");
        jLabel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setText("Consumer Studies");
        jLabel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 200, 20));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setText("Economics");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, 20));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Accounting");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, 20));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setText("Agricultural Science");
        jLabel15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 200, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel16.setText("Agricultural Technology");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel17.setText("Geography");
        jLabel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 200, 20));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel18.setText("Hospitality studies");
        jLabel18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 200, 20));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel19.setText("History");
        jLabel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 20));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel20.setText("Information Tech.");
        jLabel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, 20));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel21.setText("Life Orientation");
        jLabel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 200, 20));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel22.setText("Life Sciences");
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 200, 20));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel24.setText("Mathematics Lit.");
        jLabel24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 200, 20));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel25.setText("Physical Sciences");
        jLabel25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 200, 20));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel23.setText("Mathematics");
        jLabel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 200, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("     %");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 50, 20));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 50, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, -1));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 50, -1));
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 50, -1));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 50, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 50, -1));
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 50, -1));
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 50, -1));
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 50, -1));
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 50, -1));
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 50, -1));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 50, -1));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 50, -1));
        jPanel1.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 50, -1));
        jPanel1.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 50, -1));
        jPanel1.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 50, -1));
        jPanel1.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 50, -1));
        jPanel1.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 50, -1));
        jPanel1.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 50, -1));
        jPanel1.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 50, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setText("Subject");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, 20));
        jPanel1.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 50, -1));

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 20, 20));

        jCheckBox4.setText("jCheckBox4");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 20, 20));

        jCheckBox5.setText("jCheckBox5");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 20, 20));

        jCheckBox6.setText("jCheckBox6");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 20, -1));

        jCheckBox7.setText("jCheckBox7");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 20, -1));

        jCheckBox8.setText("jCheckBox8");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 20, -1));

        jCheckBox9.setText("jCheckBox9");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 20, -1));

        jCheckBox10.setText("jCheckBox10");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 20, -1));

        jCheckBox11.setText("jCheckBox11");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 20, -1));

        jCheckBox12.setText("jCheckBox12");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 20, -1));

        jCheckBox13.setText("jCheckBox13");
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 20, -1));

        jCheckBox14.setText("jCheckBox14");
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 20, -1));

        jCheckBox15.setText("jCheckBox15");
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 20, -1));

        jCheckBox16.setText("jCheckBox16");
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 20, -1));

        jCheckBox17.setText("jCheckBox17");
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 20, -1));

        jCheckBox18.setText("jCheckBox18");
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 20, -1));

        jCheckBox19.setText("jCheckBox19");
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 20, -1));

        jCheckBox20.setText("jCheckBox20");
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 20, -1));

        jCheckBox21.setText("jCheckBox21");
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 20, -1));

        jCheckBox22.setText("jCheckBox22");
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 20, -1));

        jCheckBox23.setText("jCheckBox23");
        jCheckBox23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox23ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 20, 20));

        jCheckBox24.setText("jCheckBox24");
        jCheckBox24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox24ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 20, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 380));

        btnSubmit.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Online Calculator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 130, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int points = 0;
    private int apsScore = 0;
    private int numberOfSubjects = 0;

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        String univers = "";
        if( numberOfSubjects >= 7){
            
        
            if (apsScore >= 15 && apsScore < 19) {
                for (int i = 0; i < 2; i++) {
                    univers += unis.get(i) + "\n";

                }
                JOptionPane.showMessageDialog(null,"You may apply at:\n" + univers, "Higher Certificate:- APS: "+apsScore, JOptionPane.INFORMATION_MESSAGE);

            } else if (apsScore >= 19 && apsScore < 26) {

                for (int i = 2; i < 6; i++) {
                    univers += unis.get(i) + "\n";

                }
                JOptionPane.showMessageDialog(null, "You may apply at:\n" + univers, "Diploma:- APS: " +apsScore, JOptionPane.INFORMATION_MESSAGE);

            } else if (apsScore >= 26) {
                for (int i = 6; i <unis.size(); i++) {
                    univers += unis.get(i) + "\n";

                }
                JOptionPane.showMessageDialog(null,"You may apply at:\n" + univers, "Bachelor:- APS: "+apsScore, JOptionPane.INFORMATION_MESSAGE);
                } else {

                    JOptionPane.showMessageDialog(null, " There are no institutions available for you!!", "Fail:-  APS: " + apsScore,JOptionPane.INFORMATION_MESSAGE);
                }
        }else {
            JOptionPane.showMessageDialog(null, "You Must at leats have 7 subjects");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed

        if (jCheckBox1.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField1.getText()) > 0 && Integer.parseInt(jTextField1.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;
                

            } else if (Integer.parseInt(jTextField1.getText()) > 29 && Integer.parseInt(jTextField1.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField1.getText()) > 39 && Integer.parseInt(jTextField1.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField1.getText()) > 49 && Integer.parseInt(jTextField1.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField1.getText()) > 59 && Integer.parseInt(jTextField1.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField1.getText()) > 69 && Integer.parseInt(jTextField1.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField1.getText()) > 79 && Integer.parseInt(jTextField1.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {
            apsScore = 0;
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed

        if (jCheckBox3.isSelected()) {
        numberOfSubjects += 1; //Increament the number of subjects
        if (Integer.parseInt(jTextField2.getText()) > 0 && Integer.parseInt(jTextField2.getText()) <= 29) {
            points = 1;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 29 && Integer.parseInt(jTextField2.getText()) <= 39) {
            points = 2;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 39 && Integer.parseInt(jTextField2.getText()) <= 49) {
            points = 3;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 49 && Integer.parseInt(jTextField2.getText()) <= 59) {
            points = 4;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 59 && Integer.parseInt(jTextField2.getText()) <= 69) {
            points = 5;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 69 && Integer.parseInt(jTextField2.getText()) <= 79) {
            points = 6;
            apsScore = apsScore + points;

        } else if (Integer.parseInt(jTextField2.getText()) > 79 && Integer.parseInt(jTextField2.getText()) <= 100) {
            points = 7;
            apsScore = apsScore + points;
        } else {
            apsScore = 0;
        }
        }

    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox3.isSelected()) {
           numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField3.getText()) > 0 && Integer.parseInt(jTextField3.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 29 && Integer.parseInt(jTextField3.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 39 && Integer.parseInt(jTextField3.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 49 && Integer.parseInt(jTextField3.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 59 && Integer.parseInt(jTextField3.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 69 && Integer.parseInt(jTextField3.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField3.getText()) > 79 && Integer.parseInt(jTextField3.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }

        } else {

        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()) {
             numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField4.getText()) > 0 && Integer.parseInt(jTextField4.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 29 && Integer.parseInt(jTextField4.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 39 && Integer.parseInt(jTextField4.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 49 && Integer.parseInt(jTextField4.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 59 && Integer.parseInt(jTextField4.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 69 && Integer.parseInt(jTextField4.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField4.getText()) > 79 && Integer.parseInt(jTextField4.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }

        } else {

        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox5.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField5.getText()) > 0 && Integer.parseInt(jTextField5.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 29 && Integer.parseInt(jTextField5.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 39 && Integer.parseInt(jTextField5.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 49 && Integer.parseInt(jTextField5.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 59 && Integer.parseInt(jTextField5.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 69 && Integer.parseInt(jTextField5.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField5.getText()) > 79 && Integer.parseInt(jTextField5.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox6.isSelected()) {
             numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField6.getText()) > 0 && Integer.parseInt(jTextField6.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 29 && Integer.parseInt(jTextField6.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 39 && Integer.parseInt(jTextField6.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 49 && Integer.parseInt(jTextField6.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 59 && Integer.parseInt(jTextField6.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 69 && Integer.parseInt(jTextField6.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField6.getText()) > 79 && Integer.parseInt(jTextField6.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox7.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField7.getText()) > 0 && Integer.parseInt(jTextField7.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 29 && Integer.parseInt(jTextField7.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 39 && Integer.parseInt(jTextField7.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 49 && Integer.parseInt(jTextField7.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 59 && Integer.parseInt(jTextField7.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 69 && Integer.parseInt(jTextField7.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField7.getText()) > 79 && Integer.parseInt(jTextField7.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox8.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField8.getText()) > 0 && Integer.parseInt(jTextField8.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 29 && Integer.parseInt(jTextField8.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 39 && Integer.parseInt(jTextField8.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 49 && Integer.parseInt(jTextField8.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 59 && Integer.parseInt(jTextField8.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 69 && Integer.parseInt(jTextField8.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField8.getText()) > 79 && Integer.parseInt(jTextField8.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox9.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField9.getText()) > 0 && Integer.parseInt(jTextField9.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 29 && Integer.parseInt(jTextField9.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 39 && Integer.parseInt(jTextField9.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 49 && Integer.parseInt(jTextField9.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 59 && Integer.parseInt(jTextField9.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 69 && Integer.parseInt(jTextField9.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField9.getText()) > 79 && Integer.parseInt(jTextField9.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox10.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField10.getText()) > 0 && Integer.parseInt(jTextField10.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 29 && Integer.parseInt(jTextField10.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 39 && Integer.parseInt(jTextField10.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 49 && Integer.parseInt(jTextField10.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 59 && Integer.parseInt(jTextField10.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 69 && Integer.parseInt(jTextField10.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField10.getText()) > 79 && Integer.parseInt(jTextField10.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }

        } else {

        }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox11.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField11.getText()) > 0 && Integer.parseInt(jTextField11.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 29 && Integer.parseInt(jTextField11.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 39 && Integer.parseInt(jTextField11.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 49 && Integer.parseInt(jTextField11.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 59 && Integer.parseInt(jTextField11.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 69 && Integer.parseInt(jTextField11.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField11.getText()) > 79 && Integer.parseInt(jTextField11.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox12.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField12.getText()) > 0 && Integer.parseInt(jTextField12.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 29 && Integer.parseInt(jTextField12.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 39 && Integer.parseInt(jTextField12.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 49 && Integer.parseInt(jTextField12.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 59 && Integer.parseInt(jTextField12.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 69 && Integer.parseInt(jTextField12.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField12.getText()) > 79 && Integer.parseInt(jTextField12.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox13.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField13.getText()) > 0 && Integer.parseInt(jTextField13.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 29 && Integer.parseInt(jTextField13.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 39 && Integer.parseInt(jTextField13.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 49 && Integer.parseInt(jTextField13.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 59 && Integer.parseInt(jTextField13.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 69 && Integer.parseInt(jTextField13.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField13.getText()) > 79 && Integer.parseInt(jTextField13.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox14.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField14.getText()) > 0 && Integer.parseInt(jTextField14.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 29 && Integer.parseInt(jTextField14.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 39 && Integer.parseInt(jTextField14.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 49 && Integer.parseInt(jTextField14.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 59 && Integer.parseInt(jTextField14.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 69 && Integer.parseInt(jTextField14.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField14.getText()) > 79 && Integer.parseInt(jTextField14.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;

            } else {

            }
        }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox15.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField15.getText()) > 0 && Integer.parseInt(jTextField15.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 29 && Integer.parseInt(jTextField15.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 39 && Integer.parseInt(jTextField15.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 49 && Integer.parseInt(jTextField15.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 59 && Integer.parseInt(jTextField15.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 69 && Integer.parseInt(jTextField15.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField15.getText()) > 79 && Integer.parseInt(jTextField15.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox16.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField16.getText()) > 0 && Integer.parseInt(jTextField16.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 29 && Integer.parseInt(jTextField16.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 39 && Integer.parseInt(jTextField16.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 49 && Integer.parseInt(jTextField16.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 59 && Integer.parseInt(jTextField16.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 69 && Integer.parseInt(jTextField16.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField16.getText()) > 79 && Integer.parseInt(jTextField16.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }

        } else {

        }
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox17.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField17.getText()) > 0 && Integer.parseInt(jTextField17.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 29 && Integer.parseInt(jTextField17.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 39 && Integer.parseInt(jTextField17.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 49 && Integer.parseInt(jTextField17.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 59 && Integer.parseInt(jTextField17.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 69 && Integer.parseInt(jTextField17.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField17.getText()) > 79 && Integer.parseInt(jTextField17.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox18.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField18.getText()) > 0 && Integer.parseInt(jTextField18.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 29 && Integer.parseInt(jTextField18.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 39 && Integer.parseInt(jTextField18.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 49 && Integer.parseInt(jTextField18.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 59 && Integer.parseInt(jTextField18.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 69 && Integer.parseInt(jTextField18.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField18.getText()) > 79 && Integer.parseInt(jTextField18.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;

            } else {

            }
        }
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox19.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField19.getText()) > 0 && Integer.parseInt(jTextField19.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 29 && Integer.parseInt(jTextField19.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 39 && Integer.parseInt(jTextField19.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 49 && Integer.parseInt(jTextField19.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 59 && Integer.parseInt(jTextField19.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 69 && Integer.parseInt(jTextField19.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField19.getText()) > 79 && Integer.parseInt(jTextField19.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox19ActionPerformed
//Life Orientation does not count
    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox20.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField20.getText()) > 0 && Integer.parseInt(jTextField20.getText()) <= 29) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 29 && Integer.parseInt(jTextField20.getText()) <= 39) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 39 && Integer.parseInt(jTextField20.getText()) <= 49) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 49 && Integer.parseInt(jTextField20.getText()) <= 59) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 59 && Integer.parseInt(jTextField20.getText()) <= 69) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 69 && Integer.parseInt(jTextField20.getText()) <= 79) {
                points = 0;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField20.getText()) > 79 && Integer.parseInt(jTextField20.getText()) <= 100) {
                points = 0;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox21.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField21.getText()) > 0 && Integer.parseInt(jTextField21.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 29 && Integer.parseInt(jTextField21.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 39 && Integer.parseInt(jTextField21.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 49 && Integer.parseInt(jTextField21.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 59 && Integer.parseInt(jTextField21.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 69 && Integer.parseInt(jTextField21.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField21.getText()) > 79 && Integer.parseInt(jTextField21.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox22.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField22.getText()) > 0 && Integer.parseInt(jTextField22.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 29 && Integer.parseInt(jTextField22.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 39 && Integer.parseInt(jTextField22.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 49 && Integer.parseInt(jTextField22.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 59 && Integer.parseInt(jTextField22.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 69 && Integer.parseInt(jTextField22.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField22.getText()) > 79 && Integer.parseInt(jTextField22.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    private void jCheckBox23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox23ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox23.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField23.getText()) > 0 && Integer.parseInt(jTextField23.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 29 && Integer.parseInt(jTextField23.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 39 && Integer.parseInt(jTextField23.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 49 && Integer.parseInt(jTextField23.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 59 && Integer.parseInt(jTextField23.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 69 && Integer.parseInt(jTextField23.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField23.getText()) > 79 && Integer.parseInt(jTextField23.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {

        }
    }//GEN-LAST:event_jCheckBox23ActionPerformed

    private void jCheckBox24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox24ActionPerformed

        if (jCheckBox24.isSelected()) {
            numberOfSubjects += 1; //Increament the number of subjects
            if (Integer.parseInt(jTextField24.getText()) > 0 && Integer.parseInt(jTextField24.getText()) <= 29) {
                points = 1;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 29 && Integer.parseInt(jTextField24.getText()) <= 39) {
                points = 2;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 39 && Integer.parseInt(jTextField24.getText()) <= 49) {
                points = 3;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 49 && Integer.parseInt(jTextField24.getText()) <= 59) {
                points = 4;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 59 && Integer.parseInt(jTextField24.getText()) <= 69) {
                points = 5;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 69 && Integer.parseInt(jTextField24.getText()) <= 79) {
                points = 6;
                apsScore = apsScore + points;

            } else if (Integer.parseInt(jTextField24.getText()) > 79 && Integer.parseInt(jTextField24.getText()) <= 100) {
                points = 7;
                apsScore = apsScore + points;
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nothing was entered");
        }
    }//GEN-LAST:event_jCheckBox24ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Object source = evt.getSource();
        Desktop desktop = Desktop.getDesktop();
           
        try {
            desktop.browse(new URI("https://whatcanistudy.co.za/aps/"));
        } catch (URISyntaxException ex) {
            Logger.getLogger(APSCalculator.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(APSCalculator.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
