//Login form
package com.yamkela22y;

import com.yamkela22y.databaseConnection.DatabaseConnection;
import com.yamkela22y.Register.Gift_Of_Education_App;
import static com.yamkela22y.databaseConnection.DatabaseConnection.close;
import com.yamkela22y.help.Help;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author YAMKELA MACWILI
 */
public class LoginForm extends javax.swing.JFrame {
    Connection conn;
    ImageIcon icon = null;
    /**
     * Creates new form SignUp
     */
    public LoginForm() {
        this.setVisible(true);
        setResizable(false);
        icon = new ImageIcon("C:\\Users\\yamke\\OneDrive\\NetBeansProjects\\IsiphoRegistrationForm\\src\\app_icons\\Background_images\\isiphoLogo_icon.jpg");
        setIconImage(icon.getImage());
        setDefaultCloseOperation(3); //JFrame.EXIT_ON_CLOSE
        setBounds(400, 200, 50, 50);//set position of the frame
        initComponents();
        txtUserNme.requestFocus();
        jlblStatusUpgate.setVisible(false);
        jlblStatusUpgate.setVisible(false); 
        
    }
    //Clear the text fields
    private void clear() {
        txtUserNme.requestFocus();
        txtUserNme.setText(null);
        JPswd.setText(null);
    }
    /**
     * 
     * @throws ClassNotFoundException
     * @throws SQLException 
     */
     public void singIn() throws ClassNotFoundException, SQLException{
        PreparedStatement pstmt;
        
        try {
            if (!"".equals(txtUserNme.getText()) || !"".equals(JPswd.getText())) {
            
                String sql = "INSERT INTO isipho_db.admins(username, password) VALUES(?,?)";
                conn = DatabaseConnection.getConnection();
                pstmt = conn.prepareStatement(sql);
                
                pstmt.setString(1, txtUserNme.getText());
                pstmt.setString(2, JPswd.getText());
                pstmt.executeUpdate(); //use exectuteQuery for select
                JOptionPane.showMessageDialog(null, "Account Created Successfully, now you can login");
                close(conn,pstmt,null); 
            }
            else{
                JOptionPane.showMessageDialog(null, "please provide username and password");
            }
                      
        } 
        catch(java.sql.SQLIntegrityConstraintViolationException duplic){
             JOptionPane.showMessageDialog(null, "User name or password is already taken");
         }
        catch (SQLException e) {
            try {
                throw e;
            } catch (SQLException ex) {
                Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
     }
     /**
      * 
      * @throws SQLException
      * @throws ClassNotFoundException 
      */
     public void login() throws SQLException, ClassNotFoundException {

        PreparedStatement pstmt;
        //Connection conn;
       
        String usname = txtUserNme.getText();
        String upass = JPswd.getText();
        try {
            String SQL = "SELECT  username,password FROM admins";
            conn = DatabaseConnection.getConnection();
            pstmt = conn.prepareStatement(SQL);
            ResultSet rs = pstmt.executeQuery(); //use exectuteQuery for select
            boolean isFound = false;
            while (rs.next()) {

                rs.getString("username");
                rs.getString("password");
                if (usname.equals(rs.getString("username")) && upass.equals(rs.getString("password"))) {
                    clear();
                    new Gift_Of_Education_App();
                    dispose();
                    isFound = true;
                } 
            }
            if(isFound == false){
                JOptionPane.showMessageDialog(null, "Wrong Username or Password!");
            }
            close(conn, pstmt, rs); //close all resources 
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(this, e);
        }finally{
            jlblStatusUpgate.setVisible(false); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUserNme = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jCheckBox = new javax.swing.JCheckBox();
        JPswd = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlblStatusUpgate = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Username");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Password");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        txtUserNme.setBackground(new java.awt.Color(204, 204, 204));
        txtUserNme.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtUserNme.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtUserNme.setToolTipText("User name");
        txtUserNme.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtUserNme.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUserNme.setName(""); // NOI18N
        txtUserNme.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNmeKeyPressed(evt);
            }
        });
        getContentPane().add(txtUserNme, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 260, 30));

        jbtnLogin.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 220, 100, -1));

        jCheckBox.setBackground(new java.awt.Color(204, 204, 204));
        jCheckBox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 20, 20));

        JPswd.setBackground(new java.awt.Color(204, 204, 204));
        JPswd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JPswd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        JPswd.setDragEnabled(true);
        JPswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JPswdKeyPressed(evt);
            }
        });
        getContentPane().add(JPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 260, 30));
        JPswd.getAccessibleContext().setAccessibleName("Password");
        JPswd.getAccessibleContext().setAccessibleDescription("Password");

        btnExit.setBackground(new java.awt.Color(153, 153, 255));
        btnExit.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 253, 100, 20));

        jLabel3.setBackground(new java.awt.Color(102, 102, 255));
        jLabel3.setForeground(new java.awt.Color(102, 102, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 410, 80));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 80, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/button_icons/login_userpasswordicon.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 80, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/button_icons/login_userpasswordicon.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 80, 60));

        jlblStatusUpgate.setFont(new java.awt.Font("Times New Roman", 3, 12)); // NOI18N
        jlblStatusUpgate.setForeground(new java.awt.Color(0, 0, 102));
        jlblStatusUpgate.setText("Please wait...");
        jlblStatusUpgate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jlblStatusUpgate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 120, -1));
        jlblStatusUpgate.getAccessibleContext().setAccessibleDescription("help ");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/Background_images/isiphoLogo_loginPage.PNG"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 620, 320));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/menu_icons/help_1_20x20.png"))); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app_icons/menu_icons/help_10x10.png"))); // NOI18N
        jMenuItem1.setText("Help");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        try {
            jlblStatusUpgate.setVisible(true); 
            login();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxActionPerformed
        if(jCheckBox.isSelected()){
            JPswd.setEchoChar((char)0);
        }
        else{
            JPswd.setEchoChar('*');
        }
        
    }//GEN-LAST:event_jCheckBoxActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
     
            System.exit(0);

    }//GEN-LAST:event_btnExitActionPerformed
    //Moves the pointer to the next field when Enter key is Pressed
    private void txtUserNmeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNmeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            JPswd.requestFocus();     
        }
    }//GEN-LAST:event_txtUserNmeKeyPressed

    private void JPswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JPswdKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try {
                login();
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_JPswdKeyPressed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        try {
            new Help();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            new Help();
        } catch (IOException ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPswd;
    private javax.swing.JButton btnExit;
    private javax.swing.JCheckBox jCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlblStatusUpgate;
    private javax.swing.JTextField txtUserNme;
    // End of variables declaration//GEN-END:variables
}
