
package com.yamkela22y;

import java.awt.Desktop;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author yamkela
 */
public class University extends javax.swing.JFrame {

    /**
     * Creates new form University
     */
    public University() {
        initComponents();
        setVisible(true);
        lblUniversity.setText("Universities".indent(50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        lblUniversity = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        btnUFH = new javax.swing.JButton();
        btnRU = new javax.swing.JButton();
        btnUNISA = new javax.swing.JButton();
        btnNMU = new javax.swing.JButton();
        btnWSU = new javax.swing.JButton();
        btnUP = new javax.swing.JButton();
        btnUFS = new javax.swing.JButton();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        btnUWC = new javax.swing.JButton();
        btnCUT = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jDesktopPane13 = new javax.swing.JDesktopPane();
        jButton17 = new javax.swing.JButton();
        jDesktopPane16 = new javax.swing.JDesktopPane();
        jButton19 = new javax.swing.JButton();
        jDesktopPane18 = new javax.swing.JDesktopPane();
        jButton4 = new javax.swing.JButton();
        jDesktopPane11 = new javax.swing.JDesktopPane();
        jButton16 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("university-application");

        lblUniversity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUniversity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDesktopPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        btnUFH.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUFH.setText("UFH");
        btnUFH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUFHActionPerformed(evt);
            }
        });

        btnRU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnRU.setText("RU");
        btnRU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRUActionPerformed(evt);
            }
        });

        btnUNISA.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUNISA.setText("UNISA");
        btnUNISA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUNISAActionPerformed(evt);
            }
        });

        btnNMU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnNMU.setText("NMU");
        btnNMU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNMUActionPerformed(evt);
            }
        });

        btnWSU.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnWSU.setText("WSU");
        btnWSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWSUActionPerformed(evt);
            }
        });

        btnUP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUP.setText("UP");
        btnUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUPActionPerformed(evt);
            }
        });

        btnUFS.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUFS.setText("UFS");
        btnUFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUFSActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(btnUFH, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnRU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnUNISA, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnNMU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnWSU, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnUP, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnUFS, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUFH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(btnUP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUFS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNMU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnWSU, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3))
                    .addComponent(btnUNISA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnWSU, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNMU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUFS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUFH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUNISA, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRU, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnNMU, btnUFS, btnWSU});

        jDesktopPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "WC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jDesktopPane6.setPreferredSize(new java.awt.Dimension(106, 314));

        btnUWC.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnUWC.setText("UWC");

        btnCUT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCUT.setText("CUT");
        btnCUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCUTActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton6.setText("CPUT");

        jButton12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton12.setText("UCT");

        jButton11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton11.setText("SUN");

        jDesktopPane6.setLayer(btnUWC, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btnCUT, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUWC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCUT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCUT, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUWC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCUT, jButton12});

        jDesktopPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("UJ");

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton8.setText("TUT");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jDesktopPane3.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton17.setText("UMP");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jDesktopPane13.setLayer(jButton17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane13Layout = new javax.swing.GroupLayout(jDesktopPane13);
        jDesktopPane13.setLayout(jDesktopPane13Layout);
        jDesktopPane13Layout.setHorizontalGroup(
            jDesktopPane13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane13Layout.setVerticalGroup(
            jDesktopPane13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton19.setText("SPU");

        jDesktopPane16.setLayer(jButton19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane16Layout = new javax.swing.GroupLayout(jDesktopPane16);
        jDesktopPane16.setLayout(jDesktopPane16Layout);
        jDesktopPane16Layout.setHorizontalGroup(
            jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane16Layout.setVerticalGroup(
            jDesktopPane16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "NW", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setText("NWU");

        jDesktopPane18.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane18Layout = new javax.swing.GroupLayout(jDesktopPane18);
        jDesktopPane18.setLayout(jDesktopPane18Layout);
        jDesktopPane18Layout.setHorizontalGroup(
            jDesktopPane18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane18Layout.setVerticalGroup(
            jDesktopPane18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane18Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "KZN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton16.setText("UNIZULU");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton20.setText("UKZN");

        jDesktopPane11.setLayer(jButton16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane11.setLayer(jButton20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane11Layout = new javax.swing.GroupLayout(jDesktopPane11);
        jDesktopPane11.setLayout(jDesktopPane11Layout);
        jDesktopPane11Layout.setHorizontalGroup(
            jDesktopPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDesktopPane11Layout.setVerticalGroup(
            jDesktopPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jButton14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton14.setText("UL");

        jDesktopPane8.setLayer(jButton14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(lblUniversity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane16))
                    .addComponent(lblUniversity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane11)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param evt 
     */
    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        String fee = "R250";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : KZN", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                JOptionPane.showMessageDialog(null, "For KZN Universities Go to : www.cao.ac.za");
                desktop.browse(new URI("www.unizulu.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UNIZULUCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * 
     * @param evt 
     */
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        String fee = "R150";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : MP", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://ump.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UMPCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * 
     * @param evt 
     */
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String fee = "R240";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : GP", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://tut.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.TUTCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnCUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCUTActionPerformed
        String fee = "FREE";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : FS", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://cut.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.CUTCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnCUTActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnUFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUFSActionPerformed
        String fee = "FREE";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://ufs.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UFSCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                }finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnUFSActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUPActionPerformed
        String fee = "R240";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : GP", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://up.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UPCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnUPActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnWSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWSUActionPerformed
        String fee = "FREE";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {

                desktop.browse(new URI("https://wsu.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.wsuCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                }finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnWSUActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnNMUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNMUActionPerformed
        String fee = "FREE";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://mandela.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.NMUCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                    //                        }finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnNMUActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnUNISAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUNISAActionPerformed
        String fee = "R120";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC | WC | KZN | ", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("www.unisa.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UNISACourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnUNISAActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnRUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRUActionPerformed
        String fee = "R100";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://ru.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.RUCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnRUActionPerformed

    /**
     * 
     * @param evt 
     */
    private void btnUFHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUFHActionPerformed
        String fee = "R120";

        String[] options = {"Proceed to application", "Application fee", "Available courses"};
        var ch = JOptionPane.showOptionDialog(null, "Province : EC", "Menu", 1, 1, null, options, null);
        switch (ch) {
            case 0:
            //                    processUpdateStart.setVisible(true);
            try {
                desktop.browse(new URI("https://ufh.ac.za"));
            } catch (URISyntaxException | IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
            break;

            case 1:
            JOptionPane.showMessageDialog(null, fee, "Application fee", 1);
            break;
            case 2:
            //                    processUpdateStart.setVisible(true);
            //                    processUpdateStart.setText("Downlaoding...");
            Read_PDF_From_URL read_PDF_From_URL = new Read_PDF_From_URL();
            {
                try {
                    read_PDF_From_URL.UFHCourses();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Universities.class.getName()).log(Level.SEVERE, null, ex);
                } finally {
                    //                             processUpdateStart.setVisible(false);
                }
            }
            default:
            break;
        }
    }//GEN-LAST:event_btnUFHActionPerformed

    Desktop desktop = Desktop.getDesktop();
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCUT;
    private javax.swing.JButton btnNMU;
    private javax.swing.JButton btnRU;
    private javax.swing.JButton btnUFH;
    private javax.swing.JButton btnUFS;
    private javax.swing.JButton btnUNISA;
    private javax.swing.JButton btnUP;
    private javax.swing.JButton btnUWC;
    private javax.swing.JButton btnWSU;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane11;
    private javax.swing.JDesktopPane jDesktopPane13;
    private javax.swing.JDesktopPane jDesktopPane16;
    private javax.swing.JDesktopPane jDesktopPane18;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JLabel lblUniversity;
    // End of variables declaration//GEN-END:variables
}
