
package com.gmail.yamkela22y.Panel;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author yamkela
 */
public class GalleryImageList extends javax.swing.JPanel {

    /**
     * Creates new form GalleryImageList
     * @param image_icon
     * @param counter
     */
    public GalleryImageList(ImageIcon image_icon, int counter) {
        initComponents();
        setVisible(true); 
        init(image_icon,counter);
    }

    private void init(ImageIcon  image_icon, int counter){
        imageAvatar1.setIcon(image_icon);
        if(image_icon.getDescription() == null){
            lblImageDesc.setText("Image "+ counter+".jgp");
        }else{
            lblImageDesc.setText(image_icon.getDescription()); 
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageAvatar1 = new com.yamkela22y.swing.ImageAvatar();
        lblImageDesc = new javax.swing.JLabel();

        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        setOpaque(false);

        imageAvatar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageAvatar1MouseClicked(evt);
            }
        });

        lblImageDesc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblImageDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImageDesc.setText("Image description");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblImageDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImageDesc))
        );
    }// </editor-fold>//GEN-END:initComponents

    Icon imageIcon = new ImageIcon();
    public Icon getImageIcon(){
        return imageIcon;
    }
    public void setImageIcon(Icon icon){
        this.imageIcon = icon;
    }
    private void imageAvatar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageAvatar1MouseClicked
        //imageIcon = imageAvatar1.getIcon();
        
        //setImageIcon(imageAvatar1.getIcon());
        Gallary.setlblImageContainer(imageAvatar1.getIcon());
        //imageAvatar1.setIcon(imageAvatar1.getIcon());
    }//GEN-LAST:event_imageAvatar1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.yamkela22y.swing.ImageAvatar imageAvatar1;
    private javax.swing.JLabel lblImageDesc;
    // End of variables declaration//GEN-END:variables
}
