package com.yamkela22y.dashboard.dialog;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

/**
 *
 * @author yamkela
 */
public class Message extends javax.swing.JPanel {

    /**
     * Creates new form Message
     *
     * @param list
     */
    public Message(ArrayList list) {
        initComponents();
        this.setVisible(true);
        setOpaque(false);
        getMessage(list);
    }

    public Message(String text) {
        initComponents();
        this.setVisible(true);
        getMessage(" " + text);
    }

//    Message m = new Message();

    private void getMessage(ArrayList list) {
        for (int i = 0; i < list.size(); i++) {
            user.setText((String) list.get(i));

        }
    }
    private void getMessage(String text) {
        message.setText(text);
    }
    
    public static void playSound(){
        InputStream input;
        try {
            input = new FileInputStream(new File("C:\\Users\\yamke\\Music\\New folder (2)\\Inkanyezi (320 kbps).mp3"));
            var audio = AudioSystem.getAudioInputStream(input); 
//            AudioStream  audio = new AudioStream(input);
//            AudioPlayer.player.start(audio);
//                
        } catch (UnsupportedAudioFileException | IOException ex) {
            java.util.logging.Logger.getLogger(Message.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        user = new javax.swing.JLabel();
        imageAvatar1 = new com.yamkela22y.swing.ImageAvatar();
        message = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);

        user.setBackground(new java.awt.Color(153, 153, 153));
        user.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        user.setText("Admin");
        user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new_icons/profile.jpg"))); // NOI18N

        message.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        message.setText("Text");
        message.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                messageMouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(user, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(imageAvatar1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(message, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(341, 341, 341)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void messageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_messageMouseClicked
        JOptionPane.showMessageDialog(jDesktopPane1, message.getText());
        
    }//GEN-LAST:event_messageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.yamkela22y.swing.ImageAvatar imageAvatar1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel message;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
